name: Fuzz DuckDb File Readers
on:
  workflow_dispatch:

jobs:
  run-aflplusplus-fuzzer:
    name: Run AFL++ fuzzer
    # dev mode: checkout branch @register_issues
    uses: duckdblabs/duckdb-aflplusplus/.github/workflows/RunFuzzer.yml@register_issues
    with:
      ref: main
      fuzzer: csv_multi_param_fuzzer
      fuzzTime: 10
    secrets:
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}
