name: Fuzz DuckDb File Readers
on:
  workflow_dispatch:

jobs:
  get-branches:
    name: Get DuckDB Branches
    runs-on: ubuntu-24.04
    outputs:
      branches: ${{ steps.call-duckdb-api.outputs.branches }}
    steps:
      - id: call-duckdb-api
        run: |
          echo "branches=$(curl -s https://api.github.com/repos/duckdb/duckdb/branches | jq -c '[.[].name]')" >> "$GITHUB_OUTPUT"

  run-aflplusplus-fuzzer:
    name: Run AFL++ fuzzer
    needs: get-branches
    # dev mode: checkout branch @register_issues
    uses: duckdblabs/duckdb-aflplusplus/.github/workflows/RunFuzzer.yml@register_issues
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.get-branches.outputs.branches) }}
        fuzzer: [csv_multi_param_fuzzer, json_multi_param_fuzzer, parquet_multi_param_fuzzer]
    with:
      fuzzer: ${{ matrix.fuzzer }}
      ref: ${{ matrix.branch }}
      fuzzTime: 10
    secrets:
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}
